php:
  preset: laravel
  version: 8.2
  enabled:
    - nullable_type_declarations
  finder:
    not-name:
      - bad-syntax-strategy.php
js:
  finder:
    exclude:
      - src/Illuminate/Foundation/resources/exceptions/renderer/dist
    not-name:
      - webpack.mix.js
css:
  finder:
    exclude:
      - src/Illuminate/Foundation/resources/exceptions/renderer/dist
