sonar.projectKey=AntoineCvlz_laravel-framework
sonar.organization=antoinecvlz

sonar.sources=.

sonar.exclusions=\
  vendor/**,\
  node_modules/**,\
  storage/**,\
  bootstrap/cache/**,\
  public/**,\
  .github/**,\
  .idea/**,\
  tests/Mocks/**,\
  tests/Fixtures/**