sonar.projectKey=AntoineCvlz_laravel-framework
sonar.organization=antoinecvlz

sonar.sources=.

sonar.exclusions=\
  vendor/**,\
  node_modules/**,\
  storage/**,\
  bootstrap/cache/**,\
  public/**,\
  .github/**,\
  .idea/**

sonar.issue.ignore.multicriteria=1
sonar.issue.ignore.multicriteria.1.resource=tests/**
sonar.issue.ignore.multicriteria.1.ruleKey=phpsecurity:*