# Projet et organisation SonarCloud
sonar.projectKey=AntoineCvlz_laravel-framework
sonar.organization=antoinecvlz

# Définition du code source et des tests
# Seul le code dans 'src' sera analysé pour les règles de sécurité
sonar.sources=src

# Les tests sont analysés pour la couverture et la qualité mais pas pour la sécurité
sonar.tests=tests

# Exclusions globales (non pertinentes pour l'analyse)
sonar.exclusions=\
  vendor/**,\
  node_modules/**,\
  storage/**,\
  bootstrap/cache/**,\
  public/**,\
  .github/**,\
  .idea/**

# Encoding des fichiers
sonar.sourceEncoding=UTF-8