# This viminfo file was generated by Vim 8.2.
# You may edit it if you're careful!

# Viminfo version
|1,4

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Last Search Pattern:
~Msle0~/\<flattenRelations\>

# Last Substitute String:
$

# Command Line History (newest to oldest):
:q
|2,0,1652162615,,"q"
:w
|2,0,1652162599,,"w"
:bd
|2,0,1652162438,,"bd"

# Search String History (newest to oldest):
? \<flattenRelations\>
|2,1,1652162550,,"\\<flattenRelations\\>"
?/flatt
|2,1,1652162549,47,"flatt"
?/par
|2,1,1652162496,47,"par"
?/dd(
|2,1,1652162426,47,"dd("
?/dd
|2,1,1652162424,47,"dd"
?/flatten
|2,1,1652162396,47,"flatten"
?/addse
|2,1,1652162385,47,"addse"

# Expression History (newest to oldest):

# Input Line History (newest to oldest):

# Debug Line History (newest to oldest):

# Registers:
""1	LINE	0
	            dd($value);
|3,1,1,1,1,0,1652162427,"            dd($value);"

# global variables:

# File marks:
'0  235  8  ~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php
|4,48,235,8,1652162615,"~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php"
'1  212  0  ~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php
|4,49,212,0,1652162604,"~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php"
'2  212  0  ~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php
|4,50,212,0,1652162604,"~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php"
'3  1  0  ~/Code/laravel/framework/test.vim
|4,51,1,0,1652162372,"~/Code/laravel/framework/test.vim"
'4  1  0  ~/Code/laravel/framework/test.vim
|4,52,1,0,1652162372,"~/Code/laravel/framework/test.vim"
'5  1  0  ~/Code/laravel/framework/test.vim
|4,53,1,0,1652162372,"~/Code/laravel/framework/test.vim"
'6  1  0  ~/Code/laravel/framework/test.vim
|4,54,1,0,1652162372,"~/Code/laravel/framework/test.vim"

# Jumplist (newest first):
-'  235  8  ~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php
|4,39,235,8,1652162615,"~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php"
-'  212  0  ~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php
|4,39,212,0,1652162604,"~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php"
-'  212  0  ~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php
|4,39,212,0,1652162604,"~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php"
-'  1511  8  ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
|4,39,1511,8,1652162583,"~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
-'  1511  8  ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
|4,39,1511,8,1652162583,"~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
-'  1439  23  ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
|4,39,1439,23,1652162551,"~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
-'  1439  23  ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
|4,39,1439,23,1652162551,"~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
-'  1422  23  ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
|4,39,1422,23,1652162550,"~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
-'  1422  23  ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
|4,39,1422,23,1652162550,"~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
-'  1421  0  ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
|4,39,1421,0,1652162549,"~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
-'  1421  0  ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
|4,39,1421,0,1652162549,"~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
-'  205  0  ~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php
|4,39,205,0,1652162535,"~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php"
-'  205  0  ~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php
|4,39,205,0,1652162535,"~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php"
-'  1478  4  ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
|4,39,1478,4,1652162512,"~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
-'  1478  4  ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
|4,39,1478,4,1652162512,"~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
-'  1435  62  ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
|4,39,1435,62,1652162503,"~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
-'  1435  62  ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
|4,39,1435,62,1652162503,"~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
-'  1448  16  ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
|4,39,1448,16,1652162428,"~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
-'  1448  16  ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
|4,39,1448,16,1652162428,"~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
-'  1502  8  ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
|4,39,1502,8,1652162426,"~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
-'  1502  8  ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
|4,39,1502,8,1652162426,"~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
-'  211  8  ~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php
|4,39,211,8,1652162425,"~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php"
-'  211  8  ~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php
|4,39,211,8,1652162425,"~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php"
-'  1  0  ~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php
|4,39,1,0,1652162414,"~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php"
-'  1  0  ~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php
|4,39,1,0,1652162414,"~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php"
-'  1501  8  ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
|4,39,1501,8,1652162401,"~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
-'  1501  8  ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
|4,39,1501,8,1652162401,"~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
-'  99  8  ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
|4,39,99,8,1652162396,"~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
-'  99  8  ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
|4,39,99,8,1652162396,"~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
-'  292  15  ~/Code/laravel/framework/src/Illuminate/Database/Query/Builder.php
|4,39,292,15,1652162391,"~/Code/laravel/framework/src/Illuminate/Database/Query/Builder.php"
-'  292  15  ~/Code/laravel/framework/src/Illuminate/Database/Query/Builder.php
|4,39,292,15,1652162391,"~/Code/laravel/framework/src/Illuminate/Database/Query/Builder.php"
-'  402  20  ~/Code/laravel/framework/src/Illuminate/Database/Query/Builder.php
|4,39,402,20,1652162387,"~/Code/laravel/framework/src/Illuminate/Database/Query/Builder.php"
-'  402  20  ~/Code/laravel/framework/src/Illuminate/Database/Query/Builder.php
|4,39,402,20,1652162387,"~/Code/laravel/framework/src/Illuminate/Database/Query/Builder.php"
-'  179  0  ~/Code/laravel/framework/src/Illuminate/Database/Query/Builder.php
|4,39,179,0,1652162385,"~/Code/laravel/framework/src/Illuminate/Database/Query/Builder.php"
-'  179  0  ~/Code/laravel/framework/src/Illuminate/Database/Query/Builder.php
|4,39,179,0,1652162385,"~/Code/laravel/framework/src/Illuminate/Database/Query/Builder.php"
-'  1  0  ~/Code/laravel/framework/src/Illuminate/Database/Query/Builder.php
|4,39,1,0,1652162378,"~/Code/laravel/framework/src/Illuminate/Database/Query/Builder.php"
-'  1  0  ~/Code/laravel/framework/src/Illuminate/Database/Query/Builder.php
|4,39,1,0,1652162378,"~/Code/laravel/framework/src/Illuminate/Database/Query/Builder.php"
-'  1  0  ~/Code/laravel/framework/test.vim
|4,39,1,0,1652162372,"~/Code/laravel/framework/test.vim"
-'  1  0  ~/Code/laravel/framework/test.vim
|4,39,1,0,1652162372,"~/Code/laravel/framework/test.vim"
-'  1  0  ~/Code/laravel/framework/test.vim
|4,39,1,0,1652162372,"~/Code/laravel/framework/test.vim"

# Buffer list:
%~/Code/laravel/framework/src/Illuminate/Database/Query/Builder.php	292	15
%~/Code/laravel/framework/test.vim	1	0
%~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php	1511	8
%~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php	235	8

# History of marks within files (newest to oldest):

> ~/Code/laravel/framework/tests/Integration/Database/EloquentMultiDimensionalArrayEagerLoadingTest.php
	*	1652162614	0
	"	235	8

> ~/Code/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php
	*	1652162572	0
	"	1511	8
	^	1502	32
	.	1448	0
	+	1502	31
	+	1448	0

> ~/Code/laravel/framework/src/Illuminate/Database/Query/Builder.php
	*	1652162388	0
	"	292	15

> ~/Code/laravel/framework/test.vim
	*	1652162367	0
	"	1	0
