#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#

FROM php:8.1-fpm

# Set Environment Variables
ENV DEBIAN_FRONTEND noninteractive

#
#--------------------------------------------------------------------------
# Software's Installation
#--------------------------------------------------------------------------
#
# Installing tools and PHP extensions using "apt", "docker-php", "pecl",
#

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
            curl \
            git \
            libzip-dev \
            libmemcached-dev \
            libz-dev \
            libicu-dev \
            libgmp-dev \
            libpq-dev \
            libjpeg-dev \
            libpng-dev \
            libfreetype6-dev \
            libssl-dev \
            libwebp-dev \
            libxpm-dev \
            libmcrypt-dev \
            libonig-dev && \
    rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-configure gd \
            --prefix=/usr \
            --with-jpeg \
            --with-webp \
            --with-xpm \
            --with-freetype && \
    docker-php-ext-install gd pdo_mysql pdo_pgsql intl gmp zip

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

COPY ./docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

WORKDIR /var/www/html

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
