<?php

namespace Illuminate\Tests\Integration\Database\SqlServer;

use Illuminate\Support\Facades\DB;

class DatabaseSqlServerMigrationsWithAlternativeDefaultSchema extends DatabaseSqlServerMigrationTest
{
    public function recreateDatabase()
    {
        parent::recreateDatabase(); // TODO: Change the autogenerated stub
        $user = "testuser";
        $schema = "test";
        $pw = 'asdf435fdgk3@asdf';

        DB::unprepared("DROP USER IF EXISTS $user;
        IF SUSER_ID('$user') IS NOT NULL DROP LOGIN $user;");

        DB::unprepared("CREATE SCHEMA $schema;");
        DB::unprepared("CREATE LOGIN $user WITH PASSWORD = '$pw';
        CREATE USER $user FOR LOGIN $user WITH DEFAULT_SCHEMA=$schema;
        EXEC sp_addrolemember N'db_owner', N'$user'
        ");
        DB::purge();
        $config = array_merge([], config('database.connections.sqlsrv'));
        $config['username'] = 'testuser';
        $config['password'] = $pw;
        config()->set('database.connections.sqlsrv2', $config);
        config()->set('database.default', 'sqlsrv2');
    }
}
