<?php

namespace Illuminate\Tests\Integration\Routing;

use Illuminate\Container\Container;
use Illuminate\Events\Dispatcher;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider;
use Illuminate\Routing\Router;
use Orchestra\Testbench\TestCase;

class RouteCacheLoadingTest extends TestCase
{
    /**
     * The path to the temporary route cache file used by the current test.
     */
    protected ?string $cachePath = null;

    /** {@inheritDoc} */
    #[\Override]
    protected function getPackageProviders($app)
    {
        return [RouteServiceProvider::class];
    }

    /** {@inheritDoc} */
    #[\Override]
    protected function tearDown(): void
    {
        if ($this->cachePath !== null && is_file($this->cachePath)) {
            @unlink($this->cachePath);
        }

        unset($_ENV['APP_ROUTES_CACHE'], $_SERVER['APP_ROUTES_CACHE']);

        parent::tearDown();
    }

    public function testItLoadsRoutesFromASerializedPayloadCacheFile()
    {
        // This is the format produced by the "route:cache" command: a require()-able
        // PHP file whose route data is stored as a serialized string.
        $this->bootWithCachedRoutes(sprintf(
            "<?php\n\napp('router')->setCompiledRoutes(\n    unserialize(%s)\n);\n",
            var_export(serialize($this->compiledRoutes()), true)
        ));

        $this->assertTrue($this->app->routesAreCached());

        $this->get('cached-route')->assertOk()->assertSee('cached response');
    }

    public function testItLoadsRoutesFromAPlainSerializedCacheFile()
    {
        // A cache file that contains only serialized route data (no PHP wrapper) is
        // read with file_get_contents()/unserialize() and handed to the router via
        // setCompiledRoutes().
        $this->bootWithCachedRoutes(serialize($this->compiledRoutes()));

        $this->assertTrue($this->app->routesAreCached());

        $this->get('cached-route')->assertOk()->assertSee('cached response');
    }

    public function testItStillLoadsLegacyVarExportCacheFiles()
    {
        // Route cache files generated by previous versions of the framework dumped
        // the compiled routes as a var_export()ed PHP array. They must keep working
        // for applications that upgrade without re-running "route:cache".
        $this->bootWithCachedRoutes(sprintf(
            "<?php\n\napp('router')->setCompiledRoutes(\n    %s\n);\n",
            var_export($this->compiledRoutes(), true)
        ));

        $this->assertTrue($this->app->routesAreCached());

        $this->get('cached-route')->assertOk()->assertSee('cached response');
    }

    /**
     * Write the given contents to a temporary route cache file and reboot the
     * application so the route service provider loads it.
     */
    protected function bootWithCachedRoutes(string $contents): void
    {
        $this->cachePath = tempnam(sys_get_temp_dir(), 'route-cache-test-');

        file_put_contents($this->cachePath, $contents);

        $_ENV['APP_ROUTES_CACHE'] = $_SERVER['APP_ROUTES_CACHE'] = $this->cachePath;

        $this->reloadApplication();
    }

    /**
     * Build a compiled route cache array containing a single named route.
     *
     * @return array{compiled: array, attributes: array}
     */
    protected function compiledRoutes(): array
    {
        $router = new Router(new Dispatcher, new Container);

        $router->get('cached-route', ['uses' => RouteCacheLoadingController::class.'@index'])->name('cached-route');

        $router->getRoutes()->refreshNameLookups();
        $router->getRoutes()->refreshActionLookups();

        return $router->getRoutes()->compile();
    }
}

class RouteCacheLoadingController
{
    public function index()
    {
        return 'cached response';
    }
}
