<?php

namespace Illuminate\Support\Facades;

/**
 * @method static never abort(int $code, string $message = '', array $headers = [])
 * @method static \Illuminate\Foundation\Application addAbsoluteCachePathPrefix(string $prefix)
 * @method static void addContextualBinding(string $concrete, string $abstract, \Closure|string $implementation)
 * @method static void addDeferredServices(array $services)
 * @method static void afterBootstrapping(string $bootstrapper, \Closure $callback)
 * @method static void afterLoadingEnvironment(\Closure $callback)
 * @method static void afterResolving(\Closure|string $abstract, \Closure|null $callback = null)
 * @method static void alias(string $abstract, string $alias)
 * @method static string basePath(string $path = '')
 * @method static void beforeBootstrapping(string $bootstrapper, \Closure $callback)
 * @method static void beforeResolving(\Closure|string $abstract, \Closure|null $callback = null)
 * @method static void bind(string $abstract, \Closure|string|null $concrete = null, bool $shared = false)
 * @method static void bindIf(string $abstract, \Closure|string|null $concrete = null, bool $shared = false)
 * @method static void bindMethod(array|string $method, \Closure $callback)
 * @method static void boot()
 * @method static void booted(callable $callback)
 * @method static void booting(callable $callback)
 * @method static string bootstrapPath(string $path = '')
 * @method static void bootstrapWith(array $bootstrappers)
 * @method static bool bound(string $abstract)
 * @method static mixed build(\Closure|string $concrete)
 * @method static mixed call(callable|string $callback, array $parameters = [], string|null $defaultMethod = null)
 * @method static mixed callMethodBinding(string $method, mixed $instance)
 * @method static string configPath(string $path = '')
 * @method static bool configurationIsCached()
 * @method static string currentLocale()
 * @method static string databasePath(string $path = '')
 * @method static string detectEnvironment(\Closure $callback)
 * @method static string|bool environment(string|array $environments)
 * @method static string environmentFile()
 * @method static string environmentFilePath()
 * @method static string environmentPath()
 * @method static bool eventsAreCached()
 * @method static void extend(string $abstract, \Closure $closure)
 * @method static \Closure factory(string $abstract)
 * @method static void flush()
 * @method static void forgetExtenders(string $abstract)
 * @method static void forgetInstance(string $abstract)
 * @method static void forgetInstances()
 * @method static void forgetScopedInstances()
 * @method static mixed Entry get(string $id Identifier of the entry to look for.)
 * @method static string getAlias(string $abstract)
 * @method static array getBindings()
 * @method static string getCachedConfigPath()
 * @method static string getCachedEventsPath()
 * @method static string getCachedPackagesPath()
 * @method static string getCachedRoutesPath()
 * @method static string getCachedServicesPath()
 * @method static array getDeferredServices()
 * @method static string getFallbackLocale()
 * @method static static getInstance()
 * @method static array getLoadedProviders()
 * @method static string getLocale()
 * @method static string getNamespace()
 * @method static \Illuminate\Support\ServiceProvider|null getProvider(\Illuminate\Support\ServiceProvider|string $provider)
 * @method static array getProviders(\Illuminate\Support\ServiceProvider|string $provider)
 * @method static \Symfony\Component\HttpFoundation\Response handle()
 * @method static bool has(string $id)
 * @method static bool hasBeenBootstrapped()
 * @method static bool hasDebugModeEnabled()
 * @method static bool hasMethodBinding(string $method)
 * @method static mixed instance(string $abstract, mixed $instance)
 * @method static bool isAlias(string $name)
 * @method static bool isBooted()
 * @method static bool isDeferredService(string $service)
 * @method static bool isDownForMaintenance()
 * @method static bool isLocal()
 * @method static bool isLocale(string $locale)
 * @method static bool isProduction()
 * @method static bool isShared(string $abstract)
 * @method static string langPath(string $path = '')
 * @method static void loadDeferredProvider(string $service)
 * @method static void loadDeferredProviders()
 * @method static \Illuminate\Foundation\Application loadEnvironmentFrom(string $file)
 * @method static \Illuminate\Contracts\Foundation\MaintenanceMode maintenanceMode()
 * @method static mixed make(string $abstract, array $parameters = [])
 * @method static mixed makeWith(string|callable $abstract, array $parameters = [])
 * @method static bool offsetExists(string $key)
 * @method static mixed offsetGet(string $key)
 * @method static void offsetSet(string $key, mixed $value)
 * @method static void offsetUnset(string $key)
 * @method static string path(string $path = '')
 * @method static void provideFacades(string $namespace)
 * @method static bool providerIsLoaded(string $provider)
 * @method static string publicPath()
 * @method static mixed rebinding(string $abstract, \Closure $callback)
 * @method static mixed refresh(string $abstract, mixed $target, string $method)
 * @method static \Illuminate\Support\ServiceProvider register(\Illuminate\Support\ServiceProvider|string $provider, bool $force = false)
 * @method static void registerConfiguredProviders()
 * @method static void registerCoreContainerAliases()
 * @method static void registerDeferredProvider(string $provider, string|null $service = null)
 * @method static \Illuminate\Support\ServiceProvider resolveProvider(string $provider)
 * @method static bool resolved(string $abstract)
 * @method static void resolving(\Closure|string $abstract, \Closure|null $callback = null)
 * @method static string resourcePath(string $path = '')
 * @method static bool routesAreCached()
 * @method static bool runningInConsole()
 * @method static bool runningUnitTests()
 * @method static void scoped(string $abstract, \Closure|string|null $concrete = null)
 * @method static void scopedIf(string $abstract, \Closure|string|null $concrete = null)
 * @method static \Illuminate\Foundation\Application setBasePath(string $basePath)
 * @method static void setDeferredServices(array $services)
 * @method static void setFallbackLocale(string $fallbackLocale)
 * @method static \Illuminate\Contracts\Container\Container|static setInstance(\Illuminate\Contracts\Container\Container|null $container = null)
 * @method static void setLocale(string $locale)
 * @method static bool shouldSkipMiddleware()
 * @method static void singleton(string $abstract, \Closure|string|null $concrete = null)
 * @method static void singletonIf(string $abstract, \Closure|string|null $concrete = null)
 * @method static string storagePath(string $path = '')
 * @method static void tag(array|string $abstracts, array|mixed ...$tags)
 * @method static iterable tagged(string $tag)
 * @method static void terminate()
 * @method static \Illuminate\Contracts\Foundation\Application terminating(callable|string $callback)
 * @method static \Illuminate\Foundation\Application useAppPath(string $path)
 * @method static \Illuminate\Foundation\Application useDatabasePath(string $path)
 * @method static \Illuminate\Foundation\Application useEnvironmentPath(string $path)
 * @method static \Illuminate\Foundation\Application useLangPath(string $path)
 * @method static \Illuminate\Foundation\Application useStoragePath(string $path)
 * @method static string version()
 * @method static string viewPath(string $path = '')
 * @method static \Illuminate\Contracts\Container\ContextualBindingBuilder when(string|array $concrete)
 * @method static \Closure wrap(\Closure $callback, array $parameters = [])
 *
 * @see \Illuminate\Contracts\Foundation\Application
 */
class App extends Facade
{
    /**
     * Get the registered name of the component.
     *
     * @return string
     */
    protected static function getFacadeAccessor()
    {
        return 'app';
    }
}
