<?php

namespace Illuminate\Support\Testing\Fakes;

use Illuminate\Config\Repository;
use Illuminate\Log\LogManager;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Date;
use Monolog\Handler\TestHandler;
use Monolog\LogRecord;

class LogFake extends LogManager implements Fake
{
    public function __construct($app, public LogManager $logManager)
    {
        parent::__construct($app);
    }

    protected function getTestingConfig(): array
    {
        return $this->app->make(Repository::class)->get('logging.channels.testing', [
            'driver' => 'monolog',
            'handler' => TestHandler::class,
        ]);
    }

    #[\Override]
    protected function resolve($name, ?array $config = null)
    {
        return parent::resolve($name, [...$this->getTestingConfig(), ...['name' => $name]]);
    }

    /**
     * @param  (\Closure(\Monolog\LogRecord): bool)|null  $callback
     * @param  string|null  $channel
     * @return Collection<int, LogRecord>
     */
    public function logged(?\Closure $callback = null, ?string $channel = null): Collection
    {
        /** @var \Monolog\Handler\TestHandler $testHandler */
        $testHandler = $this->driver($channel)->getHandlers()[0];

        $callback ??= fn () => true;

        return (new Collection($testHandler->getRecords()))
            ->filter($callback)
            ->map($this->mapLogRecordToArray(...));
    }

    protected function makeMonologDriver($handler, $with)
    {
        return parent::makeMonologDriver($handler, $with); // TODO: Change the autogenerated stub
    }

    /**
     * @param  LogRecord  $logRecord
     * @return array{"message": string, "context": array<array-key, mixed>, "level": 100|200|250|300|400|500|550|600, "level_name": "emergency"|"alert"|"critical"|"error"|"warning"|"notice"|"info"|"debug", "channel": string, "datetime": \DateTimeInterface, "extra": array<array-key, mixed>}
     */
    protected function mapLogRecordToArray(LogRecord $logRecord): array
    {
        $arr = $logRecord->toArray();
        $arr['level_name'] = strtolower($arr['level_name']);
        $arr['datetime'] = Date::make($arr['datetime']);

        return $arr;
    }
}
