name: install-nightly

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, fileinfo
          tools: composer:v2
          coverage: none

      - name: Create a Laravel application
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4
        with:
          timeout_minutes: 5
          max_attempts: 5
          shell: bash
          # rm -rf app ensures each retry starts clean in case it previously fails...
          command: rm -rf app && composer create-project laravel/laravel app --no-install --no-scripts --no-interaction

      - name: Require the development release
        working-directory: app
        run: composer require laravel/framework:13.x-dev --no-update --no-interaction

      - name: Install dependencies
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4
        with:
          timeout_minutes: 5
          max_attempts: 5
          shell: bash
          command: cd app && composer update --with-all-dependencies --no-interaction --no-progress

      - name: Boot the application
        working-directory: app
        run: php artisan about
