name: security

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.3, 8.4, 8.5 ]
        phpunit: [ '11.5.50', '12.5.8', '13.0.3' ]
        stability: [ prefer-lowest, prefer-stable ]
        exclude:
          - php: 8.3
            phpunit: '13.0.3'

    name: PHP ${{ matrix.php }} - PHPUnit ${{ matrix.phpunit }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup PHP project
        uses: ./.github/actions/setup-php-project
        with:
          php-version: ${{ matrix.php }}
          composer-command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress --with="phpunit/phpunit:~${{ matrix.phpunit }}"

      - name: Execute composer audit
        run: composer audit
