name: 'update assets'

on:
  push:
    branches:
      - master
      - '*.x'
    paths:
      - 'src/Illuminate/Foundation/resources/exceptions/renderer/**'
      - '!src/Illuminate/Foundation/resources/exceptions/renderer/dist/**'
  pull_request:
    paths:
      - 'src/Illuminate/Foundation/resources/exceptions/renderer/**'
      - '!src/Illuminate/Foundation/resources/exceptions/renderer/dist/**'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22

      - name: Update Exception Renderer Assets
        run: |
          npm ci --prefix "./src/Illuminate/Foundation/resources/exceptions/renderer"
          npm run build --prefix "./src/Illuminate/Foundation/resources/exceptions/renderer"

      - name: Commit Compiled Files
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7
        with:
          commit_message: Update Assets
